name: split_order
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^0.3.9+3
  provider: ^3.1.0+1

dev_dependencies:
  mobx_codegen: ^0.3.10+1
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/gui.png
    - assets/images/jac.png
    - assets/images/carol.png
    - assets/images/laura.png
    - assets/images/beer.jpg
    - assets/images/hot.jpg
    - assets/images/xbacon.jpg
    - assets/images/fries.jpg
